---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  "/api/v1/comments":
    post:
      summary: Create comment
      tags:
      - Comments
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: OK
          content: {}
        '422':
          description: UNPROCESSABLE ENTITY
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  properties:
                    content:
                      type: string
                    project_id:
                      type: string
                    task_id:
                      type: string
  "/api/v1/comments/{id}":
    get:
      summary: Show comments by id
      tags:
      - Comments
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
  "/api/v1/login":
    post:
      summary: Login user
      tags:
      - Users
      parameters: []
      responses:
        '401':
          description: Unauthorized
          content: {}
        '201':
          description: OK
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                password:
                  type: string
  "/api/v1/projects":
    post:
      summary: Create project
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: OK
          content: {}
        '422':
          description: 'Unprocessable Entity '
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                project:
                  properties:
                    name:
                      type: string
  "/api/v1/projects/{id}":
    get:
      summary: Show project by id
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
    patch:
      summary: Update project by id
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                project:
                  properties:
                    name:
                      type: string
    delete:
      summary: Delete project by id
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
  "/api/v1/registration":
    post:
      summary: Create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: OK
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
  "/api/v1/tasks":
    post:
      summary: Create task
      tags:
      - Tasks
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: OK
          content: {}
        '422':
          description: Invalid name
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                task:
                  properties:
                    name:
                      type: string
                    project_id:
                      type: string
  "/api/v1/tasks/{id}":
    get:
      summary: Show tasks by id
      tags:
      - Tasks
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
    patch:
      summary: Update tasks by id
      tags:
      - Tasks
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content: {}
        '404':
          description: Not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                project:
                  properties:
                    name:
                      type: string
    delete:
      summary: Delete tasks by id
      tags:
      - Tasks
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Not found
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
