---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/registration":
    post:
      summary: Create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: OK
          content: {}
        '403':
          description: Invalid params
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - name
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
